//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bell.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessageKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ErrorMessageKeys() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bell.Common.Resources.ErrorMessageKeys", typeof(ErrorMessageKeys).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to DRYIOC_CONFIGURATION_CONTAINER_SHOULD_NOT_BE_NULL.
        /// </summary>
        public static string DRYIOC_CONFIGURATION_CONTAINER_SHOULD_NOT_BE_NULL {
            get {
                return ResourceManager.GetString("DRYIOC_CONFIGURATION_CONTAINER_SHOULD_NOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ERROR_EMPTY_COLLECTION.
        /// </summary>
        public static string ERROR_EMPTY_COLLECTION {
            get {
                return ResourceManager.GetString("ERROR_EMPTY_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ERROR_HAS_OCCURRED.
        /// </summary>
        public static string ERROR_HAS_OCCURRED {
            get {
                return ResourceManager.GetString("ERROR_HAS_OCCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ERROR_NULL_VALUE.
        /// </summary>
        public static string ERROR_NULL_VALUE {
            get {
                return ResourceManager.GetString("ERROR_NULL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to OBJECT_TYPE_SHOULD_BE_AN_INTERFACE.
        /// </summary>
        public static string OBJECT_TYPE_SHOULD_BE_AN_INTERFACE {
            get {
                return ResourceManager.GetString("OBJECT_TYPE_SHOULD_BE_AN_INTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_DATETIME.
        /// </summary>
        public static string VALIDATION_ERROR_DATETIME {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_DATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_EMAIL.
        /// </summary>
        public static string VALIDATION_ERROR_EMAIL {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_EMPTY.
        /// </summary>
        public static string VALIDATION_ERROR_EMPTY {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_ENUMERATION.
        /// </summary>
        public static string VALIDATION_ERROR_ENUMERATION {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_ENUMERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_EQUAL.
        /// </summary>
        public static string VALIDATION_ERROR_EQUAL {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_EXACT_LENGTH.
        /// </summary>
        public static string VALIDATION_ERROR_EXACT_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_EXACT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_EXCLUSIVE_BETWEEEN.
        /// </summary>
        public static string VALIDATION_ERROR_EXCLUSIVE_BETWEEEN {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_EXCLUSIVE_BETWEEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_GREATER_THAN.
        /// </summary>
        public static string VALIDATION_ERROR_GREATER_THAN {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_GREATER_THAN_OR_EQUAL.
        /// </summary>
        public static string VALIDATION_ERROR_GREATER_THAN_OR_EQUAL {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_GREATER_THAN_OR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_INCLUSIVE_BETWEEN.
        /// </summary>
        public static string VALIDATION_ERROR_INCLUSIVE_BETWEEN {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_INCLUSIVE_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_LENGTH.
        /// </summary>
        public static string VALIDATION_ERROR_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_LESS_THAN.
        /// </summary>
        public static string VALIDATION_ERROR_LESS_THAN {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_LESS_THAN_OR_EQUAL.
        /// </summary>
        public static string VALIDATION_ERROR_LESS_THAN_OR_EQUAL {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_LESS_THAN_OR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_NOT_EMPTY.
        /// </summary>
        public static string VALIDATION_ERROR_NOT_EMPTY {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_NOT_EQUAL.
        /// </summary>
        public static string VALIDATION_ERROR_NOT_EQUAL {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_NOT_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_NOT_NULL.
        /// </summary>
        public static string VALIDATION_ERROR_NOT_NULL {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_NULL.
        /// </summary>
        public static string VALIDATION_ERROR_NULL {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_PREDICATE.
        /// </summary>
        public static string VALIDATION_ERROR_PREDICATE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_PREDICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERROR_REGEX.
        /// </summary>
        public static string VALIDATION_ERROR_REGEX {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VALIDATION_ERRORS.
        /// </summary>
        public static string VALIDATION_ERRORS {
            get {
                return ResourceManager.GetString("VALIDATION_ERRORS", resourceCulture);
            }
        }
    }
}
